[package]
name = "bidrum-controller-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bidrum-data-struct-lib = { path = "../data-struct-lib" }
serialport = "4.3.0"
device_query = "2.0.0"